//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by tmidi.rc
//
#define IDD_MAIN                        101
#define IDI_ICON                        103
#define IDI_PLAY                        104
#define IDI_PAUSE                       105
#define IDI_STOP                        106
#define IDD_TEXT                        107
#define IDD_ASSOC                       108
#define IDD_TRACKS                      109
#define IDD_SYSEX                       110
#define IDD_CHANNELS                    111
#define IDB_GMLOGO                      114
#define IDB_GSLOGO                      115
#define IDB_XGLOGO                      116
#define IDB_MTLOGO                      117
#define IDD_GENERIC_TEXT                118
#define IDM_MAIN                        119
#define IDD_OUTCONFIG                   120
#define IDR_241                         123
#define IDC_OPEN                        1000
#define IDC_ANALYSIS                    1001
#define IDC_FILENAME                    1002
#define IDC_MIDI_OUT                    1003
#define IDC_MIDI_IN                     1004
#define IDC_PLAY                        1005
#define IDC_STOP                        1006
#define IDC_TIME                        1007
#define IDC_PAUSE                       1007
#define IDC_T0                          1008
#define IDC_T1                          1009
#define IDC_T2                          1010
#define IDC_T3                          1011
#define IDC_T4                          1012
#define IDC_T5                          1013
#define IDC_T6                          1014
#define IDC_T7                          1015
#define IDC_T8                          1016
#define IDC_T9                          1017
#define IDC_T10                         1018
#define IDC_T11                         1019
#define IDC_T12                         1020
#define IDC_T13                         1021
#define IDC_T14                         1022
#define IDC_T15                         1023
#define IDC_TICK                        1024
#define IDC_EVENTSLABEL                 1025
#define IDC_EVENTS                      1026
#define IDC_EVENTSLABEL2                1027
#define IDC_SONGLENLABEL                1027
#define IDC_SONG_LENGTH                 1028
#define IDC_EVENTSLABEL3                1029
#define IDC_EVENTSLABEL4                1030
#define IDC_CURRENT_TIME                1031
#define IDC_TRIGGER_TIME                1032
#define IDC_DISPLAY_TEXT                1033
#define IDC_DISPLAY_TRACKS              1034
#define IDC_DISPLAY_SYSEX               1035
#define IDC_DISPLAY_CHANNELS            1036
#define IDC_CONTROLLERS                 1037
#define IDC_SONGPOS                     1049
#define IDC_SONG_SLIDER                 1049
#define IDC_EVENTPOS                    1050
#define IDC_EVENT_SLIDER                1050
#define IDC_POLYPHONY_METER             1051
#define IDC_POLYPHONY                   1052
#define IDC_TEXT_LIST                   1052
#define IDC_CURRENT_TEXT                1053
#define IDC_TEMPO_SLIDER                1054
#define IDC_GOAWAY                      1054
#define IDC_VELOCITY_SLIDER             1055
#define IDC_PITCH_SLIDER                1056
#define IDC_PITCH                       1057
#define IDC_VELOCITY                    1058
#define IDC_C0                          1059
#define IDC_C1                          1060
#define IDC_C2                          1061
#define IDC_C3                          1062
#define IDC_C4                          1063
#define IDC_C5                          1064
#define IDC_C6                          1065
#define IDC_C7                          1066
#define IDC_C8                          1067
#define IDC_C9                          1068
#define IDC_C10                         1069
#define IDC_C11                         1070
#define IDC_C12                         1071
#define IDC_C13                         1072
#define IDC_C14                         1073
#define IDC_C15                         1074
#define IDC_CHECK16                     1076
#define IDC_TRACKS_LIST                 1077
#define IDC_SYSEX_LIST                  1078
#define IDC_CHANNELS_LIST               1079
#define IDC_MIDI_OUT_STATIC             1080
#define IDC_MIDI_IN_STATIC              1081
#define IDC_POLYPHONY_STATIC            1082
#define IDC_MIDI_LOGO                   1083
#define IDC_GENERIC_TEXT                1084
#define IDC_LIST1                       1086
#define IDC_OUT_DEV_LIST                1086
#define IDC_DEV_NAME                    1087
#define IDC_MS_MT32                     1089
#define IDC_MS_GM                       1090
#define IDC_MS_GS                       1091
#define IDC_MS_XG                       1092
#define IDC_USABLE                      1093
#define IDC_DEV_MANUFACTURER            1094
#define IDC_DEV_ID                      1095
#define IDC_LOOP                        1095
#define IDC_DEV_TYPE                    1096
#define IDC_ALL_INSTR                   1096
#define IDM_FILE_EXIT                   40001
#define IDM_FILE_OPEN                   40002
#define ID_HELP_ABOUT                   40003
#define IDM_OUTCONFIG                   40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
